prometheus:
  sources:
    - url: "http://192.168.1.10:8088/metrics"
      label: "device1"
    - url: "http://192.168.1.11:8088/metrics"
      label: "device2"

mqtt:
  broker: "tcp://mqtt:1883"
  client_id: "wingbits-mqtt"
  topic_base: "homeassistant/sensor/wingbits/"
  username: "mqttusername"
  password: "mqttpassword"

fetch_interval_seconds: 60
